name = "saleor-tma-api"
main = "dist/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_ENV = "production"

# Environment-specific settings
[env.production]
name = "saleor-tma-api"

[env.staging]
name = "saleor-tma-api-staging"
route = "saleor-tma-api.live-nature.net/*"
